#!/usr/bin/env bash

set -e

# TODO: delete this script, the entry in `package.json`, and the subcommand in
# `Procfile` - it's only used for the Graphile Starter demo.

if [ "x$DEMO" != "xWIPE_DATABASE" ]; then
  echo "This script is only intended to be used when deploying the Graphile Starter demo to Heroku, since we reset the database every time we push."
  exit 1;
fi;

if [ "x$DATABASE_URL" = "x" ]; then
  echo "No database URL.";
  exit 2;
fi;

${PSQL:psql} "${DATABASE_URL/?ssl=1/}" <<HERE
  DROP SCHEMA IF EXISTS graphile_migrate, graphile_worker, app_public, app_hidden, app_private CASCADE;
HERE

# Reinstall the worker schema
cd ../worker
yarn install-db-schema
