#!/usr/bin/env bash

if [ -f ./.envvar ]; then
  echo "Using existing .envvar"
  . ./.envvar
else
  DOCKER_MODE="n"
fi

if [ "$DOCKER_MODE" = "y" ]; then
  echo "Starting up docker"
  docker-compose up
else
  echo "Starting up servers directly"
  yarn dev
fi
