/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */


declare module '*/AddEmail.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const AddEmail: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/ChangePassword.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const ChangePassword: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/ConfirmAccountDeletion.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const ConfirmAccountDeletion: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/CurrentUserAuthentications.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const CurrentUserAuthentications: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/CurrentUserUpdated.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const CurrentUserUpdated: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/DeleteEmail.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const DeleteEmail: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/EmailsForm_User.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const EmailsForm_User: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/EmailsForm_UserEmail.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const EmailsForm_UserEmail: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/ForgotPassword.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const ForgotPassword: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/Login.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const Login: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/Logout.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const Logout: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/MakeEmailPrimary.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const MakeEmailPrimary: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/ProfileSettingsForm_User.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const ProfileSettingsForm_User: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/Register.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const Register: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/RequestAccountDeletion.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const RequestAccountDeletion: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/ResendEmailVerification.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const ResendEmailVerification: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/ResetPassword.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const ResetPassword: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/SettingsEmails.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const SettingsEmails: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/SettingsPassword.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const SettingsPassword: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/SettingsProfile.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const SettingsProfile: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/SharedLayout.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const SharedLayout: DocumentNode;
export const SharedLayout_User: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/UnlinkUserAuthentication.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const UnlinkUserAuthentication: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/UpdateUser.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const UpdateUser: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/VerifyEmail.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const VerifyEmail: DocumentNode;

  export default defaultDocument;
}
    