version: "3.7"
services:
  dev:
    # Uncomment the next line to use a non-root user. On Linux, this will prevent
    # new files getting created as root, but you may need to update the USER_UID
    # and USER_GID in .devcontainer/Dockerfile to match your user if not 1000.
    # user: node

    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FORCE_COLOR=2
      - DOCKER_MODE
      - DATABASE_HOST
      - DATABASE_OWNER

    volumes:
      - ../graphile-starter-project:/app
      - node_modules-volume:/app/node_modules
    working_dir: /app
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - default
    ports:
      # The main server
      - 5678:5678
      # Node `--inspect=...` port numbers for debugging
      - 9678:9678
      - 9876:9876
      - 9757:9757
    links:
      - pg

  pg:
    image: postgres:11
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - default
    restart: unless-stopped
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/var/lib/postgresql/data/logs -c log_rotation_age=60 -c log_truncate_on_rotation=on -c log_filename=server_log.hour.%H%M

networks:
  default:
    name: graphile-starter

volumes:
  db-volume:
  node_modules-volume:
