#!/bin/bash

# Exit on error
set -e

# Source our configuration variables
. ./scripts/env

# Dear graphile-migrate, please treat the test DB as if it were the shadow DB
export SHADOW_DATABASE_URL="$TEST_DATABASE_URL"

# Signal to graphile-migrate scripts that we're in the tests
export IN_TESTS="1"

# Reset the test database
graphile-migrate reset --shadow
graphile-migrate watch --once --shadow

# If we're in watch mode
if [[ "$*" == "--watch" ]] || [[ "$*" == "--watchAll" ]]; then
  # We're in watch mode, so keep watching the `current.yml` file
  concurrently \
    --names 'tests,___db' \
    --kill-others \
    "node --inspect=9876 node_modules/.bin/jest -i $@" \
    'graphile-migrate watch --shadow'
else
  # Run once, so just run the tests
  jest -i "$@"
fi;
